apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
spec:
  type: LoadBalancer
  ports:
    - name: http  # Adding a name for the HTTP port
      port: 8080
      targetPort: 8080
    - name: https  # Adding a name for the HTTPS port
      port: 8443
      targetPort: 8443
  selector:
    app: keycloak

